name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: extension

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        working-directory: extension
        run: |
          python -m pip install --upgrade pyinstaller

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          pyinstaller -F main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: extension/dist
